v8:
	gcc -Wall shuffle.c client.c v8.c

v7:
	gcc -Wall shuffle.c client.c v7.c

v6:
	gcc -Wall client.c v6.c

v5:
	gcc -Wall client.c v5.c

v4:
	gcc -Wall client.c v4.c

v3:
	gcc -Wall client.c v3.c

v2:
	gcc -Wall client.c v2.c

v1:
	gcc -Wall client.c v1.c

clean:
	rm -f *.o a.out
